### thymeleaf reactive
GET http://localhost:8080

### Route Hi
GET http://localhost:8080/hi

### item reactive request
GET http://localhost:8080/item/1

### cloud function
POST http://localhost:8080/uppercase
Content-Type: text/plain

demo

###